spring:

  application:
    name: Show fast and furious movies

  datasource:
    url: mem:///data/fast-and-furious
    username: sa
    password:

  jackson:
    default-property-inclusion: non_absent
    serialization.write_enums_using_to_string: true
    deserialization.read_enums_using_to_string: true

  r2dbc:
    url: r2dbc:h2:${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  flyway:
    url: jdbc:h2:${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: PUBLIC
    sqlMigrationPrefix: V
    sqlMigrationSuffix: .sql
    sqlMigrationSeparator: _

logging:

  file: logs/file.log
  pattern:
    console: '%d %-5level [%thread] %logger : %msg%n'
    file: '%d %-5level [%thread] %logger : %msg%n'
  level:
    org.springframework.data.r2dbc: debug
    com.cronusrhea: debug

server:
  port: 8090

  http2:
    enabled: true
